### ISSUE TITLE
Selecing Marry or James by tapping on them and delete

### ISSUE THREAD

**Issue by RajChanchal** [soleaf/MintAnnotationView#2]
Thanks for the awesome tool, let me know if it is possible to implement the selecting a tagged person (like iMessages) and pressing back button to delete them?

**Comment by oy-ilho** [comment]
Hello.
It maybe able That Implementing Selecting tag to delete. 
Sorry. but I couldn’t spend time for this project now. 
If you can make this function, I appreciate you.

I made it using NSAttributedString  to tag ID(Custom Attribute) on Characters.
If Character have a Tag ID, view draw button or image on the character position.
Therefore,  You can make it by checking Tag ID  on Character  and other action at some event.

Thank you.
