### ISSUE TITLE
Tap Handler in MintAnnotationMemoView

### ISSUE THREAD

**Issue by SalvatoreAD** [soleaf/MintAnnotationView#4]
It's possible to import library in Swift?

**Comment by oy-ilho** [comment]
Sorry
I have never tried.
I have quitted iOS app developer when use Objective-C
Could you try It?

2017년 8월 3일 (목) 오후 3:32, SalvatoreAD <notifications@github.com>님이 작성:

**Comment by SalvatoreAD** [comment]
I solved creating a bridge. In your opinion, is it possible to click on the tag in MemoView?

**Comment by oy-ilho** [comment]
You can add event on tag.

https://github.com/soleaf/MintAnnotationView/blob/master/MintAnnotationView/MintAnnotationView/MintAnnotationMemoView.m#L142 <https://github.com/soleaf/MintAnnotationView/blob/master/MintAnnotationView/MintAnnotationView/MintAnnotationMemoView.m#L142>

 UILabel *tagLabel = [[UILabel alloc] initWithFrame:titleRect];

Tags are UILabel Object. So You can replace this UILabel to UIButton.
Then You can free to add event  tags.

If you need implementation of this idea, I can help you. (maybe next weekend)
But I think It’s better that you contribute to this project through push your code :)

**Comment by SalvatoreAD** [comment]
Of course, I made a change, but I can not create an event click.

I've changed your code, but I do not know how to enter the event. I'm not good at objc

```
UIButton *tagButton = [UIButton buttonWithType:UIButtonTypeCustom];
    tagButton.frame = CGRectMake(titleRect.origin.x,
                                 titleRect.origin.y+1,
                                 titleRect.size.width,
                                 titleRect.size.height);
    
    [tagButton setBackgroundImage:self.nameTagImage forState:UIControlStateNormal];
    [tagButton setTitle:nameText forState:UIControlStateNormal];
    [tagButton setTitleColor:self.nameTagColor forState:UIControlStateNormal];
    tagButton.titleLabel.font = [UIFont systemFontOfSize:self.font.pointSize-4];
    [self addSubview:tagButton];

```

**Comment by oy-ilho** [comment]
Using a delegate to pass event action  to a controller  will be able.
I will try It after some days and reply.

**Comment by SalvatoreAD** [comment]
@soleaf thanks

**Comment by SalvatoreAD** [comment]
@soleaf Some news about it?

**Comment by oy-ilho** [comment]
Now, You can use event for tag.
Let your' UIController Implements "MintAnnotationMemoViewDelegate" like CommentListViewController on MintAnnotationViewSample.
